### ISSUE TITLE
Set toast display timers to 5 seconds

### ISSUE THREAD

**Issue by jkrogers18** [GoogleCloudPlatform/fda-mystudies#2333]
Current toasts are displayed for ~1 second, which is difficult to read.

**Comment by harisboston** [comment]
@firdosebtc1 @prakashm181 Issue is fixed for sig-in screen (oauth server), need to be fixed for other screens, front-end changes required.

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in QA

**Comment by Lathan-btc** [comment]
@firdosebtc1 Following messages are displayed only for 3 seconds
1. Set up account > Success message
2. Password help screen - success message

**Comment by firdosebtc1** [comment]
> @firdosebtc1 Following messages are displayed only for 3 seconds
> 
> 1. Set up account > Success message
> 2. Password help screen - success message

@Lathan-btc I have fixed this ,please check

**Comment by Lathan-btc** [comment]
@firdosebtc1 Issue is still reproducing in latest QA instance

**Comment by nishit-v** [comment]
@harisboston this should be handled for Study Builder also. Currently error messages timers are set to 3 seconds. Should be set to 5 seconds.

**Comment by firdosebtc1** [comment]
> > @firdosebtc1 Following messages are displayed only for 3 seconds
> > 
> > 1. Set up account > Success message
> > 2. Password help screen - success message
> 
> @Lathan-btc I have fixed this ,please check

@prakashm181 please check this issue

**Comment by firdosebtc1** [comment]
@Lathan-btc please check this issue in QA

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by harisboston** [comment]
@nishit-v Fix is deploying in dev environment, kindly test and update this ticket. 
Increased the error message timers to 5 seconds.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by harisboston** [comment]
@Lathan-btc Fix is deployed in QA environment, kindly test and update this ticket.

**Comment by nishit-v** [comment]
Issue is still observed in SB for account lock toast message.

Refer attached video:

https://user-images.githubusercontent.com/60386291/108851783-d0d06180-760a-11eb-98e2-7a36e2168b20.mp4

**Comment by nishit-v** [comment]
Reverified the above scenario along in other modules. Working fine in QA and Dev.
