### ISSUE TITLE
To change term 'user' to 'admin' in the error and message codes of PM, also in PM emails

### ISSUE THREAD

**Issue by sharathblr** [GoogleCloudPlatform/fda-mystudies#2433]
Replace the word user with admin in the error and message codes of PM.

Also, we need to replace them in the emails of PM.

**Comment by Lathan-btc** [comment]
@chiranjibi009 
1. Deactivated Admin
AR : 'User deactivated successfully' is displayed
ER ' Admin user deactivated successfully' should be displayed 

![deactivate admin](https://user-images.githubusercontent.com/71445210/103092797-7290fd80-461e-11eb-8626-f0a9f3244c30.png)


2. Delete admin
AR : 'The invitation for this user has been deleted' is displayed
ER : 'The invitation for this admin has been deleted' should be displayed

![delete invitation](https://user-images.githubusercontent.com/71445210/103092804-7a50a200-461e-11eb-9b64-982cd7ee67d9.png)

**Comment by Lathan-btc** [comment]
@sharathblr please confirm Expected result for the above scenarios.

**Comment by chiranjibi009** [comment]
@firdosebtc1 please correct these from angular side

**Comment by firdosebtc1** [comment]
@Lathan-btc I have fixed this issue in QA, please check

**Comment by Lathan-btc** [comment]
@firdosebtc1 issue is still reproducible for the following scenario 
Delete admin
AR : 'The invitation for this user has been deleted' is displayed
ER : 'The invitation for this admin has been deleted' should be displayed

![error msg1](https://user-images.githubusercontent.com/71445210/103504134-86d5c580-4e7c-11eb-8b24-65eda5c8dc63.png)

**Comment by firdosebtc1** [comment]
@Lathan-btc please check Error and Validation Messages V1.1 sheet, It is same as sheet

![image](https://user-images.githubusercontent.com/60000166/103504894-bc7bae00-4e7e-11eb-9b71-3acd9a60fed8.png)

**Comment by firdosebtc1** [comment]
> @firdosebtc1 issue is still reproducible for the following scenario
> Delete admin
> AR : 'The invitation for this user has been deleted' is displayed
> ER : 'The invitation for this admin has been deleted' should be displayed
> 
> ![error msg1](https://user-images.githubusercontent.com/71445210/103504134-86d5c580-4e7c-11eb-8b24-65eda5c8dc63.png)

@Lathan-btc I have updated this in QA, Please check

**Comment by Lathan-btc** [comment]
@firdosebtc1 Issue is fixed in latest QA instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
