### ISSUE TITLE
[Mobile Apps] Study Activities > Custom schedule should show next run coming up when current run has expired/completed/missed

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#2757]
Current behavior:  Only the first run of the custom schedule is being shown even though its expired/completed/missed

Expected: Custom schedule should show next run coming up when current run has expired/completed/missed

**Comment by nagarjunav1** [comment]
Issue is fixed in latest DEV build in Android

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA Android build.

**Comment by nishit-v** [comment]
@amruthbtc Issue should be handled for below scenarios in iOS.

**Scenario 1:** PAST section - Expired runs should show all runs

Actual: Expired runs not showing all runs

Expected: Expired runs should show all runs (refer android)

iOS:
![IMG_1802](https://user-images.githubusercontent.com/60386291/125743935-91be798a-ec53-44d4-83b5-67c67064c8f9.PNG)

Android:
![Screenshot_20210715-115521_FDA MyStudies](https://user-images.githubusercontent.com/60386291/125744014-75ab750b-2908-4397-8d1c-064d26349627.jpg)

**Scenario 2:** CURRENT section - Past runs not displaying

Actual: Past runs not displaying

Expected: Past runs should show all runs (refer android)

iOS:
![iOS](https://user-images.githubusercontent.com/60386291/125744601-079433a3-bd18-475a-ac7b-f383604c2929.png)

Android:
![Android](https://user-images.githubusercontent.com/60386291/125744617-b3a57745-3a98-4a2d-b212-2879d8db3a5a.jpg)

**Comment by nishit-v** [comment]
Issue is not fixed for the above two scenarios mentioned .

Past runs not displaying in Current and Past section.

![unnamed](https://user-images.githubusercontent.com/60386291/128500947-364149a0-6cdd-4338-8afe-3b492e3a8f05.png)

**Comment by nishit-v** [comment]
Issue is not resolved completely.

1. Anchor date based questionnaires and active tasks not showing past runs in 'Past' section

![Screenshot 2021-08-11 at 12 21 23 PM](https://user-images.githubusercontent.com/60386291/128983027-8b122b0a-35ac-4edb-841d-42beb4e58a48.png)


2. Clicking on pop-up in current section not showing all the expired runs

![IMG_1878](https://user-images.githubusercontent.com/60386291/128982933-dc557ffb-90fa-4541-93f4-0112cc7c76c0.PNG)

![IMG_1880](https://user-images.githubusercontent.com/60386291/128982947-3550da3e-0d67-44fd-9db5-ed52e0d5d9c0.PNG)

**Comment by nishit-v** [comment]
Issue should be handled for below 2 scenarios:

1. Anchor based activities having past runs showing empty runs 
![1](https://user-images.githubusercontent.com/60386291/130565871-07e8f6c8-b764-4b65-b941-006d4a896f5d.png)


2. If activity in current having past runs, Total run count and missed runs should not be counted for past runs.
![2](https://user-images.githubusercontent.com/60386291/130565967-1730c6a6-d908-4cf2-9df9-abc8da63dce3.png)

**Comment by nishit-v** [comment]
Issue is fixed in latest iOS dev build V10.5

**Comment by nishit-v** [comment]
Issue is fixed in latest iOS QA build V10(29)
