### ISSUE TITLE
[Android] [Audit Logs] "userID" is displayed null for the events

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#2989]
Event:- 
1. PASSWORD_RESET_SUCCEEDED

Sample snippet
```
{
  "insertId": "1xxk52ag3ixdmsf",
  "jsonPayload": {
    "description": null,
    "resourceServer": "PARTICIPANT USER DATASTORE",
    "appId": "BTCDEV001",
    "userIp": "157.45.162.176",
    "destination": "SCIM AUTH SERVER",
    "mobilePlatform": "ANDROID",
    "occurred": 1611240030322,
    "userAccessLevel": null,
    "siteId": null,
    "participantId": null,
    "destinationApplicationVersion": "1.0",
    "sourceApplicationVersion": "1.0",
    "correlationId": "SCJfbJLx83G45JpSFBeYYtE6tEESvAuvJPNkiqshEiPJfV8BhP",
    "studyId": null,
    "appVersion": "1.0.58",
    "userId": null,
    "source": "MOBILE APPS",
    "eventCode": "PASSWORD_RESET_SUCCEEDED",
    "platformVersion": "1.0",
    "studyVersion": null
  },
  "resource": {
    "type": "global",
    "labels": {
      "project_id": "mystudies-open-impl-track1-dev"
    }
  },
  "timestamp": "2021-01-21T14:40:30.322Z",
  "severity": "INFO",
  "logName": "projects/mystudies-open-impl-track1-dev/logs/application-audit-log",
  "receiveTimestamp": "2021-01-21T14:40:30.452503878Z"
}
```

**Comment by Kantharajut-btc** [comment]
@nagarjunav1 this issue is fixed in dev please check and confirm

**Comment by nishit-v** [comment]
Issue is not fixed and "userID" is still displayed null

![Screenshot_6](https://user-images.githubusercontent.com/60386291/105500643-2bfbf500-5ce9-11eb-95ea-f2e7c497988f.png)

**Comment by Kantharajut-btc** [comment]
@nagarjunav1 this issue is fixed in dev, please check and confirm

**Comment by nagarjunav1** [comment]
```
{
  "insertId": "jpamcufweqk2h",
  "jsonPayload": {
    "eventCode": "PASSWORD_RESET_SUCCEEDED",
    "appVersion": "1.0.60",
    "userId": "5501df3098fedb42d5p95d1g021ae87bc13c",
    "userIp": "157.45.42.79",
    "platformVersion": "1.0",
    "correlationId": "NNZ4cYHzW8zT49aKkhxgBMqRwGVxSps8lZUBPEn7ZAGriMKUcP",
    "mobilePlatform": "ANDROID",
    "occurred": 1611585088022,
    "studyVersion": null,
    "source": "MOBILE APPS",
    "resourceServer": "PARTICIPANT USER DATASTORE",
    "destination": "SCIM AUTH SERVER",
    "participantId": null,
    "destinationApplicationVersion": "1.0",
    "description": null,
    "studyId": null,
    "sourceApplicationVersion": "1.0",
    "appId": "BTCDEV001",
    "siteId": null,
    "userAccessLevel": null
  },
  "resource": {
    "type": "global",
    "labels": {
      "project_id": "mystudies-open-impl-track1-dev"
    }
  },
  "timestamp": "2021-01-25T14:31:28.022Z",
  "severity": "INFO",
  "logName": "projects/mystudies-open-impl-track1-dev/logs/application-audit-log",
  "receiveTimestamp": "2021-01-25T14:31:28.155131268Z"
}
```
Issue is fixed in latest DEV build
