### ISSUE TITLE
[PM] Title is getting highlighted

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3021]
AR : Title is getting highlighted when user mouse hovered on the page title for the following screens
       1. Add new location
       2. About
       3. Terms of service
 ER : Title should not be highlighted

![title1](https://user-images.githubusercontent.com/71445210/105684199-a8294f00-5f1a-11eb-82f6-4d9e2fac16de.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have fixed please check and close the issue.

**Comment by Lathan-btc** [comment]
@Madhud5 Issue is still reproducible for the following pages
1. About
2. Terms of service


![abt](https://user-images.githubusercontent.com/71445210/106254248-82fc4f80-623e-11eb-902e-c40f78886447.png)


![tos](https://user-images.githubusercontent.com/71445210/106254247-82fc4f80-623e-11eb-897d-df0c4e1a36fb.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have fixed please check and close the issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.
