### ISSUE TITLE
[PD] Emails sent to study participants must use study-specific support email address

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3115]
Emails sent to participants of a specific study (for study invitations) must contain the support contact email address specific to the study, and as configured in the Study Builder

**Comment by chiranjibi009** [comment]
@nishit-v Please test this issue creating new study in dev environment and update.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by chiranjibi009** [comment]
@Lathan-btc Please test this issue creating new study in QA environment. If fixed close the issue

**Comment by nishit-v** [comment]
@chiranjibi009 Issue is not resolved if contact email address in SB has 1 or 2 length username in email address eg. `a@grr.la` `a1@grr.l`a  

![Screenshot_1](https://user-images.githubusercontent.com/60386291/109168362-be8a2b00-77a4-11eb-920a-0d2801fdcc3a.png)

**Comment by nishit-v** [comment]
Issue is resolved in QA and Dev instance after rechecking for newly created studies.

![Screenshot_1](https://user-images.githubusercontent.com/60386291/109260138-9beb2700-7823-11eb-8801-02f8c218e1a0.png)
