### ISSUE TITLE
[SB] Provide secure access URLs for resources 

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3297]
URLs for accessing resources from the study datastore should have secure access protection and must not be publicly accessible. Please check for various types of resources on the SB and address where not already fixed.

**Comment by dhanyak-btc** [comment]
@moschetti [ Signed URLs](https://cloud.google.com/storage/docs/access-control/signed-urls) can be used to access resources in Cloud Storage. A signed URL is a URL that provides limited permission and time to make a request. We can set the duration in minutes. Please suggest if any better solutions to provide secure resources stored on Cloud Storage.

**Comment by moschetti** [comment]
What is the context of the request? What resources are you talking about accessing, and who/what is accessing them?

**Comment by dhanyak-btc** [comment]
@moschetti Default images and Image(s) that are uploaded from Study Builder during Study creation are stored on Cloud Storage public bucket. These images are accessed by Mobile Apps and Participant Manager.

**Comment by moschetti** [comment]
I think signed URLs should be ok, but setting a time duration may be an issue as we would need them to be accessible all the time, correct?

**Comment by madhurya-btc** [comment]
Signed URLs will be generated in GET operations hence not stored in database. Can we set 12 hours of duration for the signed URLs?

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test all the images, logo in SB , PM and Mobile App by creating new study.

**Comment by Lathan-btc** [comment]
@madhurya-btc not able to test this issue due to #3442

**Comment by madhurya-btc** [comment]
@Lathan-btc #3442 issue is fixed , Please test and confirm

**Comment by Lathan-btc** [comment]
@madhurya-btc 
Thumbnail images are not displaying in PM

![img123](https://user-images.githubusercontent.com/71445210/114355728-72951900-9b8d-11eb-9baf-0b3b2d384e02.png)

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test and confirm

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by madhurya-btc** [comment]
@Lathan-btc Please test one more time as cloud bucket is changed to private.

**Comment by nishit-v** [comment]
Issue is still observed in Mobile apps. Thumbnail images and overview images are not loading
![a](https://user-images.githubusercontent.com/60386291/114870206-805ccf80-9e15-11eb-97bb-5a250be5aaac.png)

**Comment by madhurya-btc** [comment]
@nishit-v Please test and confirm in dev instance

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by madhurya-btc** [comment]
Please test and confirm in QA instance.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance.
