### ISSUE TITLE
[SB] Modify text format for inline errors

### ISSUE THREAD

**Issue by SR-btc** [GoogleCloudPlatform/fda-mystudies#3383]
For all inline error messages that are short phrases and single sentences, remove the period at the end of the sentence. E.g.
'Please fill out this field'

**Comment by chiranjibi009** [comment]
@Lathan-btc Please test the issue in dev environment and update

**Comment by Lathan-btc** [comment]
Issue is still reproducible in the latest Dev instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc  i have checked in DEV its fixed. Please check and let me know.

**Comment by Madhud5** [comment]
Hi @latha  i have checked in DEV its fixed. Please check and let me know.

**Comment by Madhud5** [comment]
Hi @latha  i have checked in DEV its fixed. Please check and let me know.

**Comment by Madhud5** [comment]
Hi @latha  i have checked in DEV its fixed. Please check and let me know.

**Comment by Lathan-btc** [comment]
@Madhud5 Issue is reproducible for the following
1. Questionnaires > Question level attributes > line chart and stats
2. Questionnaires > Response level attributes - It should be fixed for all the response types

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have checked in DEV its fixed. Please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is reproducible in the latest Dev instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc I have fixed in DEV- QA. Please check and close the issue.

**Comment by Lathan-btc** [comment]
@Madhud5 Issue is still reproducible in the latest QA instances 

Questionnaires/Active task >Shcedule tab > Other than one-time frequency > it should be fixed for both regular and anchor date

**Comment by Madhud5** [comment]
Hi @Lathan-btc  i have checked in DEV its fixed. Please check and let me know.

**Comment by Lathan-btc** [comment]
@Madhud5 Issue is reproducible for the following scenario
Questionnaires > Response level attributes - It should be fixed for all the response types - the issue is reproducible for the Form step

**Comment by Madhud5** [comment]
Hi @Lathan-btc  i have checked in DEV its fixed. Please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by nishit-v** [comment]
Issue is fixed in the latest QA instance.
