### ISSUE TITLE
[PM] Responsive issues in Admins

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3472]
Responsive issues in Users
1. Admins > Edit admins details > Deactivate /Active admin Ui issue

![mba1](https://user-images.githubusercontent.com/71445210/115354130-ec08b900-a1d6-11eb-8f0d-0af7dd11bdbc.png)

![mba2](https://user-images.githubusercontent.com/71445210/115354673-8406a280-a1d7-11eb-9bdd-581967a35917.png)

2. Admins > Admin details page > UI issues > Values are wrapping up with the margins

![mba3](https://user-images.githubusercontent.com/71445210/115355283-258df400-a1d8-11eb-89e3-06a95ab78e8c.png)

3. Manage admins page > Table UI issue and contents are wrapping with the margins

![mba4](https://user-images.githubusercontent.com/71445210/115357071-e2348500-a1d9-11eb-841e-21c8fe6566bf.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc i have checked in DEV its fixed. Please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc I have fixed it. Please check and close the issue.

**Comment by Lathan-btc** [comment]
@Madhud5 issue is still reproducible in latest QA instance 
1. Admin details page

![userdetailspa](https://user-images.githubusercontent.com/71445210/120888698-68384e00-c617-11eb-8a0d-2c06524a0a00.png)

![admin3](https://user-images.githubusercontent.com/71445210/120888709-75edd380-c617-11eb-98ab-725ea4f9a04a.png)


2. Add admin

![newadmin](https://user-images.githubusercontent.com/71445210/120888713-843bef80-c617-11eb-8e92-790c088f4c8c.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc Please check and let me know.

**Comment by Lathan-btc** [comment]
@Madhud5 Issue is reproducible in the latest Dev instance.

![admin32](https://user-images.githubusercontent.com/71445210/121715171-31bd7000-cafc-11eb-9a21-0c815becadee.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc Please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is fixed n the latest Dev instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc Issue is fixed in the latest QA instance.

**Comment by Lathan-btc** [comment]
@Madhud5 issue is reproducible in the latest QA instance.
1. Edit admin details
2. Add admin

![admin321](https://user-images.githubusercontent.com/71445210/122360025-b3d1ec80-cf73-11eb-9702-12ceca00d3ce.png)

**Comment by Madhud5** [comment]
Hi @Lathan-btc Please check and let me know.

**Comment by Lathan-btc** [comment]
Issue is still reproducible in the latest Dev and QA instance.

**Comment by Madhud5** [comment]
Hi @Lathan-btc Please check and let me know.

**Comment by Lathan-btc** [comment]
issue is fixed in the latest Dev instance.

**Comment by aswinijena100** [comment]
@nagarjunav1 Please test it in QA and close if fixed

**Comment by nagarjunav1** [comment]
Issue is fixed in latest QA build
