### ISSUE TITLE
[SB] [Import] Questionnaires/Active task > Schedule > Selected anchor date type is not imported into new study 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3678]
**Steps**
1. Login to SB
2. Create/Edit study
3. Add questionnaires/ active task/Resources with an anchor date based schedule type
4. Import the particular study
5. Click on the edit button of the new study
6. Navigate to Questionnaires and Active task section
7. Switch to the schedule tab
8. Observe the value 'Select anchor date type' dropdown

**AR:** Anchor date type is not imported into new study
**ER:** All the contents should be imported into a new study

[Note: Issue should be fixed in questionnaires, Active task and Resources]

**Comment by Kantharajut-btc** [comment]
@Lathan-btc this issue is fixed in dev, please check and confirm.

**Comment by Lathan-btc** [comment]
@Kantharajut-btc  Issue is still reproducible for the Resources.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc please retest this issue in dev and update the ticket accordingly.

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev instance.

**Comment by Kantharajut-btc** [comment]
@Lathan-btc  please test this issue in QA and confirm.

**Comment by nishit-v** [comment]
Issue is fixed in the latest Dev instance.
