### ISSUE TITLE
[SB] Questionnaires/Active task > Regular > Schedule tab > Issues in custom schedule 

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#3724]
Questionnaires/Active task > Schedule tab > Issues in custom schedule 

1. End time field is allowing lesser time than the start time when a user enters the same date for both start date and end date fields
2. It is allowing overlapping dates and time  
3. It is validating when the dates and time got overlapped but still allowing the user to click on the done button and the user is able to launch/publish the updates  
4. Active task > user is not able to enter the same date for both start date and end date 

![custom121](https://user-images.githubusercontent.com/71445210/121370983-d0aa6680-c95a-11eb-8100-2f6f56219a7e.png)

**Comment by harisboston** [comment]
@Lathan-btc Issue is fixed in dev environment, kindly test and update this ticket

**Comment by Lathan-btc** [comment]
@harisboston 
1. Not validating when the user enters overlapping times
2. Allowing the user to Click on the Done button


![custom21](https://user-images.githubusercontent.com/71445210/121717794-36cfee80-caff-11eb-9b49-4ae8c871d302.png)

**Comment by Lathan-btc** [comment]
@harisboston Issue is still reproducible in the latest Dev instance.

![custom13](https://user-images.githubusercontent.com/71445210/121846321-7e739780-cd04-11eb-81c7-a9a57139722f.png)

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev and QA instance.
