### ISSUE TITLE
[SB] [Import] Custom schedule > Order of the runs is incorrect in GetStudyActivityList API for imported study hence scheduling in mobile apps is incorrect

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#3803]
Steps:
1. Edit a study
2. Add custom schedule regular/anchor based > 2 runs
3. Publish updates
4. Export and import the study
5. Launch the imported study
6. Compare the GetStudyActivityList AP for original and imported study

Actual: Order of the runs is incorrect which is causing mobile apps scheduling behave indifferently 

Expected: Order should be same as of original study 

Note:
Issue observed for questionnaires and active tasks
Issue observed for regular and anchor based
Issue observed only for custom schedule

Study details:
Instance: Dev
Original study: Eyedisease
Imported study: imported0759

![Screenshot_2](https://user-images.githubusercontent.com/60386291/122946648-2b9a7f80-d397-11eb-9f53-91c96ffeacb8.png)

![Screenshot_1](https://user-images.githubusercontent.com/60386291/122946746-40771300-d397-11eb-94aa-a9193a7b2bdb.png)

**Comment by harisboston** [comment]
@nishit-v Issue is fixed in dev env, kindly test and update this ticket

**Comment by nishit-v** [comment]
Issue is partially fixed. `"start"` and `"end"` array for anchordate is showing incorrect values for imported study

![Screenshot_3](https://user-images.githubusercontent.com/60386291/122966619-29402180-d3a7-11eb-9ee7-6004d8fcfa3a.png)

[Left side- Original, Right side - Imported]

**Comment by nishit-v** [comment]
Issue is resolved in latest Dev instance.

**Comment by nishit-v** [comment]
Issue is resolved in latest QA instance. (Before PR)

**Comment by nishit-v** [comment]
Issue is resolved in latest QA instance. (After PR)

**Comment by nishit-v** [comment]
Issue is resolved in latest QA instance. (After PR)
