### ISSUE TITLE
[SB] Issue related to anchor date based custom scheduling

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4053]
Steps:

1. Click on edit study.
2. Navigate to questionnaries.
3. Add/Edit the questionnaries.
4. Click on Schedule tab.
5. Add Anchor date > custom schedule.
6. Enter all the values and click on save button.
7. Remove the values from anchor date, start time and end time fields.
8. Click on done button and Observe.

AR: Validation messages are not displaying for anchor date and start time fields.
ER: Validation messages should be displayed for anchor date and start time fields.

Note: Issue needs to be fixed for both questionnaries and active task.

![P1Issue _2](https://user-images.githubusercontent.com/86007179/131118233-c6695729-ec9d-453e-becc-eaac7ec35331.png)

**Comment by rithikbtc** [comment]
@bhoomikav16 This issue is resolved . Please verify and confirm

**Comment by bhoomikav16** [comment]
@rithikbtc  Issue is still reproduciable in the Questionnaires section

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev instance.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance.
