### ISSUE TITLE
[SB] UI issue > Daily scheduling options > Time(s) of the day for daily occurrence 

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4061]
**Steps:**

1. Edit the study.
2. Navigate to active tasks section.
3. Click on add active task button.
4. Choose active task from dropdown.
5. Navigate to Schedule tab.
6. Select daily scheduling options.
7. Click on plus icon beside "Time(s) of the day for daily occurrence" field and Observe the first row in  Time(s) of the day for daily occurrence.

**AR:**Delete  icon is not getting displayed for the first row.
**ER:**Delete icon should be displayed for the first row also.

**Note:** 1. Issue needs to be fixed for both Active tasks and Questionnaires.
                2. Issue needs to be fixed for both regular and anchor date based schedule type.

![Untitled33](https://user-images.githubusercontent.com/86007179/131529907-096553aa-de26-421d-9bce-d38b028d23ee.png)

**Comment by Kantharajut-btc** [comment]
@bhoomikav16 this issue is fixed in dev, please check and confirm.

**Comment by bhoomikav16** [comment]
@Kantharajut-btc  Issue is still reproduciable in Questionnaires section for both regular and anchor date based schedule type.

**Comment by Kantharajut-btc** [comment]
@bhoomikav16 please test this issue in dev and update the ticket accordingly.

**Comment by bhoomikav16** [comment]
@Kantharajut-btc  Issue is still reproduciable in dev

**Comment by Kantharajut-btc** [comment]
@bhoomikav16 please test this issue in dev and QA. Update the ticket accordingly

**Comment by bhoomikav16** [comment]
Issue is fixed in latest dev and QA instance.
