### ISSUE TITLE
[SB] Issues in summer note editor

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#4337]
Steps:- 
1. Login into SB 
2. Type/Paste the content in multiple paragraphs in Summer note editor
3.  Select multiple paragraphs and modify the Font size or Font Style 
4. Observe the behavior of the summer note

A/R:- Only first paragraph is updated with the latest changes 
E/R:- All the selected paragraphs should be updated with the latest changes

Note:- Issue should be fixed for all the summer note editor fields across application

 Refer attached video

https://user-images.githubusercontent.com/60500517/148023925-e5e822a1-2cfd-4670-b832-c14dd244b644.mp4

**Comment by aswinijena100** [comment]
@nagarjunav1 issue is fixed and deployed in dev . Please test and confirm

**Comment by nagarjunav1** [comment]
Issue is still reproducing in DEV instance
https://user-images.githubusercontent.com/60500517/149347641-34aaf1dc-7af0-4348-b5ff-e2b425252ff2.mp4

**Comment by Madhud5** [comment]
Hi @nagarjunav1 issue is fixed and deployed in dev . Please test and confirm

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest DEV build

**Comment by Madhud5** [comment]
Hi @nagarjunav1 pls check and close this ticket.
thank you

**Comment by Madhud5** [comment]
Hi @nagarjunav1 pls check and close this ticket.
thank you

**Comment by nagarjunav1** [comment]
Issue is fixed now in latest QA build
