### ISSUE TITLE
[SB] UI Issue in all the popup messages which comes in the action screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4385]
UI Issue is observed in all the popup messages which comes in the action screen.

Note: Can refer the popup message which comes when we add non-organizational user in the study builder.

![q](https://user-images.githubusercontent.com/86007179/150551813-24151574-26d6-4691-9fa9-a1cc305a53d0.png)

**Comment by Lathan-btc** [comment]
@Madhud5 UI of the popups should be the same as below popup (Refer: While adding non-organizational admins in the 'Add admin' screen)

![image](https://user-images.githubusercontent.com/71445210/151813437-669efc0f-97df-4c4a-a0a4-2ce72ae8d3a1.png)

**Comment by Madhud5** [comment]
Hi @bhoomikav16, please check this issue in dev and let me know.
thank you

**Comment by bhoomikav16** [comment]
@Madhud5 
**AR:** Cross mark is getting dispalyed in the pause action popup message.
**ER:** Cross mark should not get dispalyed in the pause action popup message.
Note: Issue is observed only for pause action
![Untitled](https://user-images.githubusercontent.com/86007179/152151082-ae6dc2b9-233b-4c6c-ba02-cfa293fd1c85.jpg)

**Comment by Madhud5** [comment]
Hi @bhoomikav16 , please check this issue in dev and let me know.
thank you

**Comment by bhoomikav16** [comment]
@Madhud5 Issue is fixed in the latest dev instance

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest QA instance

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest QA build

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest QA instance

![qa](https://user-images.githubusercontent.com/86007179/164212650-6339950d-7891-4eb2-bef1-6877827a9b54.png)

**Comment by madhurya-btc** [comment]
@bhoomikav16 Please test and confirm in the QA instance

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
