### ISSUE TITLE
[Android] Failure message should be changed , which comes when participants are not eligible for the study in the standalone app

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4582]
**Steps:**
1. Install the standalone app
2. Sign up
3. Click on Participate button
4. Fail the eligibility process 
5. Now, Verify the failure message

**AR:** Getting message as attached in the below screenshot

![Android1](https://user-images.githubusercontent.com/86007179/165768472-a815c29b-21de-4593-82e7-94243ac9928e.png)

**ER:** Failure message should be changed , which comes when participants are not eligible for the study in the standalone app

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev build 1.0(166)

**Comment by Lathan-btc** [comment]
The issue is fixed in the latest Dev build 3.0(48)

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.185

**Comment by Lathan-btc** [comment]
Issue is still reproducible in the latest QA iOS build V3.0.187

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA build 1.0(218)
