### ISSUE TITLE
[IDP] [SB] [PM] Add admin > Getting an error message for 'Phone' number field even when entered valid inputs

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4608]
**Steps:** 
1. In Add admin screen, Click on phone number field
2. Enter the valid input based on the format (Eg: +91-9999999999 ) and Verify

**AR:**  Getting an error message as "Phone number is invalid"
**ER:**  Phone number field should accept valid inputs
![phone number](https://user-images.githubusercontent.com/86007179/170715412-feee66db-b41c-4269-acdb-a819c9ca0b64.png)

**Comment by harshith2590** [comment]
Hi Haris,
We can remove the Hyphen symbol in the format and give a space between country code and number. This might solve the issue.

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest Dev instance

**Comment by bhoomikav16** [comment]
Issue is  still reproducing in the latest dev instance

![phonefield](https://user-images.githubusercontent.com/86007179/171167130-5940f2b6-1f99-4bff-b1dd-c60a8fc57d40.png)

**Comment by bhoomikav16** [comment]
Phone number format should be similar in both SB and PM

**Comment by bhoomikav16** [comment]
UI of Phone number format should be similar in both SB and PM

**Comment by bhoomikav16** [comment]
Functionality of phone number is working fine. UI issue in the phone number format is tracked in separate issue.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest IDP QA branch
