### ISSUE TITLE
[PM] Studies > Study participant registry > Search bar placeholder text should be changed

### ISSUE THREAD

**Issue by nishit-v** [GoogleCloudPlatform/fda-mystudies#4752]
Actual: "Search by site ID or participant email"

Expected: "Search by site name or participant email"

Note: Functionality wise, search results are getting displayed if admin searches by site name and NOT site ID. Hence we have to specify name intead of ID in placeholder text

![Screenshot_3](https://user-images.githubusercontent.com/60386291/180806374-8f21c13e-5f71-447f-b30f-8495445b2898.png)

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest Dev build

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the VAPT branch , Broken placeholder name is getting displayed

**Comment by Madhud5** [comment]
Hi @Lathan-btc please check and close the issue.
thanks

**Comment by Lathan-btc** [comment]
Issue is fixed in the latest QA instance
