### ISSUE TITLE
[Android][Branching] User will able to submit the responce for the other questions which are not related to the branching in a scenario

### ISSUE THREAD

**Issue by nagarjunav1** [GoogleCloudPlatform/fda-mystudies#4963]
Steps:- 
1. Navigate to Questionnaries
2. Add a new questionnarie
3. Configure the questionnarie as shown in image 1 & image 2
4. Apply internal branching for the same questionnarie based on user input
5. Publish the study
6. Open the same questionnarie in mobile and submit the responces as shown in the attached video

A/R:- Participant is able to answer the questions, which are not related to branching logic in the scenario 
E/R:- Disable the device back button in completion screen or Participant should not be able to answer the questions which are not related to the final responce provided for branching question

Image 1
![image](https://user-images.githubusercontent.com/60500517/190648346-5c6d8888-9a7e-40db-9298-fa222f6910b0.png)

Image 2
![image](https://user-images.githubusercontent.com/60500517/190648485-1a16d434-8bf7-4ee7-981a-de6d405aa8c4.png)

Android
https://user-images.githubusercontent.com/60500517/190648584-dcc955dc-b028-401d-b702-1a088374fdce.mp4

**Comment by nagarjunav1** [comment]
Issue is fixed in latest Dev build v1.0(210)

Disabled the device back button in completion screen

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest android build 1.0(213)

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest android dev build 1.0(214)

Please refer the attached screenshot and video below to reproduce the issue

**Image1:**
![image](https://user-images.githubusercontent.com/86007179/192303650-f937b3cb-e83f-421d-855d-a815fb3a7845.png)


**Image 2:**
![image](https://user-images.githubusercontent.com/86007179/192303508-f9524f12-d027-4c6a-bac5-4e23e56351f2.png)

https://user-images.githubusercontent.com/86007179/192304557-14af1adb-8536-4a44-a9a4-3462cf79e10d.mp4

**Comment by Shashank-btc** [comment]
Hi

This issue will happen only when the last screen is the instruction step. Please close the ticket if main issue is resolved.

Thanks

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest android dev build 1.0(214)

Please refer the attached screenshot and video below to reproduce the issue

Image1:
![image](https://user-images.githubusercontent.com/86007179/192479463-0731f496-877c-4b0c-a24c-ee326d4b6767.png)

Image2:
![image](https://user-images.githubusercontent.com/86007179/192479578-61d25706-0dd0-419c-bcf7-fa4879b88686.png)


https://user-images.githubusercontent.com/86007179/192479950-ed8c7a96-e526-4812-b3cf-af3dace4bad3.mp4

**Comment by Shashank-btc** [comment]
Hi
Reverting the applied changes for the branching logic and we will update the way of implementation as it invloves researchstack(framework)

**Comment by nagarjunav1** [comment]
Main issue is fixed now in the latest build v1.0(214). Found navigation issue for the instruction step in the flow and will be tracked seperately in #5017

**Comment by nagarjunav1** [comment]
Issue is fixed now in the latest QA build
