### ISSUE TITLE
[Consent API] Consent record with revoked state should be created ,when participant account is deleted in the mobile app

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#4995]
**Pre-condition:** Closed/combined/ iOS open study should be created in the study builder

**Steps:**
1. Sign in / Sign up
2. Enroll for the closed / combined study and then withdrawn from the study
3. Open the PM , and add same user account for different site in the PM
4. Then Open the mobile app
5. Again enroll for the same study
6. Go to 'My account' section and delete the user account
7. Go to that particular consent record and Verify

**AR:** Consent record with revoked state is not getting created ,when participant account is deleted in the mobile app
**ER:** Consent record with revoked state should be created ,when participant account is deleted in the mobile app

**Note:** 
1. Issue is observed only when same user account is added in different sites in the participant manager
2. Issue is not observed when same user account is added in the same site in the participant manager

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest dev instance

**Note:** Issue is observed only when submitted response from Android 12 device

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest android dev build 1.0(213)

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest QA instance

**Comment by Lathan-btc** [comment]
@harisboston Issue is still reproducible in the latest QA instance

**Comment by akashkumarv3** [comment]
@Lathan-btc Issue is fixed in QA, please check and update.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest QA instance
