### ISSUE TITLE
[Mobile apps] Stats and Charts(Trends) functionality is not working

### ISSUE THREAD

**Issue by Lathan-btc** [GoogleCloudPlatform/fda-mystudies#5016]
AR: Stats and Charts(Trends) functionality is not working > Values are not getting displayed in the stats and charts when the participant provides the response for the activities
ER: Stats and Chart functionality should work as expected

**Comment by akashkumarv3** [comment]
Hi Team, from backend it is resolved, and Values are coming in correct structure.

**Comment by akashkumarv3** [comment]
Hi @GovindPrasadBostonTechnologyCorporation @Shashank-btc , issue is resolved from backend, Mobile team please check and update this ticket.

**Comment by nagarjunav1** [comment]
Issue is fixed in latest Dev build

**Comment by nishit-v** [comment]
Issue is fixed in latest QA iOS build V3.0.186

**Comment by Lathan-btc** [comment]
@akashkumarv3 

**Charts** 
1.  If the user submits the values for any run it is displayed as the last run of the activity
2. Fetal kick counter > Values are showing as 0

[Note: for android users > same issue observed once user logged out and logged in ]

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest dev instance i.e., 
For form step > Charts and stats > 'No data' is getting displayed in charts and 'NA' is getting displayed for stats , even though the mobile user provided the response

**Comment by akashkumarv3** [comment]
@Lathan-btc   For form step > Charts and stats > chart and stats is working now, please check and update

**Comment by bhoomikav16** [comment]
Issue is fixed in the both VAPT dev and QA instance
