### ISSUE TITLE
[IDP] [SB] Getting 'Invalid format' error when try to sign in study builder

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#5073]
**Pre-condition-** IDP and MFA should be enabled in the study builder

**Steps:**
1. Add admins in the study builder by entering the value in the phone number field which should be as similar in the format displayed in the UI
2. After getting account setup link in an email, click on that link
3. Complete all the fields and click on Submit button 
4. Now, Try to sign in with same credentials and Verify

**AR:** Getting 'Invalid format' error when try to sign in study builder and not able to sign in
**ER:** Admin should be able to sign in without any error's

![Error](https://user-images.githubusercontent.com/86007179/199656754-fb835fef-8ad6-438e-8070-fffdd2578380.png)

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest IDP branch, Getting 'Too_Long' error message when tried to sign in with organizational admin account

![image (9)](https://user-images.githubusercontent.com/86007179/199704561-9e9a6866-21a7-4a1e-8065-82ebb2638156.png)

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest IDP branch, Getting 'Too_Long' error message when tried to sign in with organizational admin account and not able to sign in

**Comment by akashkumarv3** [comment]
@bhoomikav16 Issue is fixed now, please check and update.

**Comment by bhoomikav16** [comment]
Issue is still reproducing in the latest IDP branch, Getting 'Too_Long' error message when tried to sign in with organizational admin account and not able to sign in

**Comment by Lathan-btc** [comment]
@akashkumarv3 
As discussed with the BA team, please change the mobile format for both SB and PM as mentioned below

+X XXX XXX XXXX

**Comment by Lathan-btc** [comment]
@akashkumarv3 Issue should also be fixed for PM


![image](https://user-images.githubusercontent.com/71445210/200328651-fd6446ad-cde4-4ac6-be80-911ce01b1575.png)

**Comment by akashkumarv3** [comment]
@Lathan-btc Issue is fixed in PM also please check and update .

**Comment by bhoomikav16** [comment]
@akashkumarv3  Issue is still reproducing in 'My account' screen. Phone number format is not accepting the input as in the UI

**Comment by bhoomikav16** [comment]
Issue is observed in account creation flow also

**Comment by madhud-btc** [comment]
Hi @bhoomikav16 issue fixed pls check in dev and confirm.
thank you.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest PM IDP dev branch

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest IDP QA branch
