### ISSUE TITLE
 [SB] UI Issue >  Questionnaires / Active task > Error messages are overlapping in the scheduling screen

### ISSUE THREAD

**Issue by bhoomikav16** [GoogleCloudPlatform/fda-mystudies#5094]
Questionnaires / Active task > Error messages are overlapping in the scheduling screen

![UII](https://user-images.githubusercontent.com/86007179/203248109-38f868ed-1384-4b4a-8a84-f8d1254e99da.png)

**Note:** 
1. Issue needs to be fixed for both Questionnaires and Active tasks
2. Issue needs to be fixed for all scheduling options

**Comment by akashkumarv3** [comment]
Hi @bhoomikav16  Issue is fixed now ,please check and update.

**Comment by bhoomikav16** [comment]
Issue is still reproducing,

 For active task i.e., No space between error message and the field
![active task](https://user-images.githubusercontent.com/86007179/203266100-af953ec9-3fe8-4d9e-90fd-c67630b11df5.png)
For questionnaires, Anchor date and one time > Error message is getting displayed out of the screen
![Questionnaires](https://user-images.githubusercontent.com/86007179/203266294-de93c043-c003-4df2-9d5f-eeb29661457f.png)

Alignment issue is observed after saving the data in the scheduling screen [Observed in both Questionnaires and active task]
![Alignment](https://user-images.githubusercontent.com/86007179/203267116-5b5b7952-3064-4eca-b656-1b8f19d8ffe2.png)

**Comment by madhud-btc** [comment]
Hi @bhoomikav16 please check this ticket and close.
thanks

**Comment by bhoomikav16** [comment]
Issue is reproducing in the latest dev and QA instance for anchor date scheduling option

**Comment by akashkumarv3** [comment]
@bhoomikav16 Hi, Issue is fixed both dev and qa env now in all scenarios. please check and update.

**Comment by bhoomikav16** [comment]
Issue is fixed in the latest dev and QA instance
